[versions]
agp = "8.11.2"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.11.0"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.5"
androidx-testExt = "1.3.0"
composeMultiplatform = "1.9.1"
junit = "4.13.2"
kotlin = "2.2.20"
kotlinxSerializationJson = "1.9.0"
navigationCompose = "2.9.6"


koinBom ="4.1.1"
ktor = "3.3.1"
coil-version = "3.3.0"

sqlite = "2.5.0-alpha11"
roomVersion = "2.7.0"
kspVersion = "2.2.20-2.0.2"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

#---KOIN---
koin-bom = {module = "io.insert-koin:koin-bom" , version.ref = "koinBom"}
koin-core = { module= "io.insert-koin:koin-core" }
koin-android = { module="io.insert-koin:koin-android"}
koin-androidx-compose = { module="io.insert-koin:koin-androidx-compose"}
koin-compose-viewmodel = { module="io.insert-koin:koin-compose-viewmodel"}


#---KTOR---
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }

#-----COIL-----
coil-compose-core = { group = "io.coil-kt.coil3", name = "coil-compose-core", version.ref = "coil-version" }
coil-network-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil-version" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil-version" }

#nav
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

#serialize
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

#Room
androidx-room-runtime = {group = "androidx.room" , name="room-runtime" , version.ref = "roomVersion"}
androidx-room-ktx = {group = "androidx.room" , name="room-ktx",version.ref = "roomVersion"}
androidx-room-compiler = {group = "androidx.room" , name = "room-compiler" , version.ref = "roomVersion"}

sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
#serialization
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization" , version.ref = "kotlin"}
#ksp plugin
devtools-ksp = { id = "com.google.devtools.ksp" , version.ref ="kspVersion"}
androidx-room = { id = "androidx.room", version.ref = "roomVersion" }



